// Code generated by protoc-gen-go.
// source: router.proto
// DO NOT EDIT!

/*
Package router is a generated protocol buffer package.

It is generated from these files:
	router.proto

It has these top-level messages:
	Test
	ModuleMachine
	ModuleInfo
	GetRouteRequest
	GetRouteResponse
	GetModuleRouteListRequest
	GetModuleRouteListResponse
	UpdateRouteRequest
	UpdateRouteResponse
	ReLoadRouteNotify
	Request
	Response
*/
package router

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}
var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Test struct {
	Label            *string             `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32              `protobuf:"varint,2,opt,name=type,def=77" json:"type,omitempty"`
	Reps             []int64             `protobuf:"varint,3,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *Test_OptionalGroup `protobuf:"group,4,opt,name=OptionalGroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Test_Type int32 = 77

func (m *Test) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Test_Type
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetOptionalgroup() *Test_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type Test_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req,name=RequiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test_OptionalGroup) Reset()                    { *m = Test_OptionalGroup{} }
func (m *Test_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*Test_OptionalGroup) ProtoMessage()               {}
func (*Test_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Test_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

type ModuleMachine struct {
	ModuleId         *string `protobuf:"bytes,1,req,name=module_id" json:"module_id,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Weight           *int32  `protobuf:"varint,3,req,name=weight" json:"weight,omitempty"`
	CreateUser       *string `protobuf:"bytes,4,opt,name=createUser" json:"createUser,omitempty"`
	CreateTime       *string `protobuf:"bytes,5,opt,name=createTime" json:"createTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModuleMachine) Reset()                    { *m = ModuleMachine{} }
func (m *ModuleMachine) String() string            { return proto.CompactTextString(m) }
func (*ModuleMachine) ProtoMessage()               {}
func (*ModuleMachine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ModuleMachine) GetModuleId() string {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return ""
}

func (m *ModuleMachine) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *ModuleMachine) GetWeight() int32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

func (m *ModuleMachine) GetCreateUser() string {
	if m != nil && m.CreateUser != nil {
		return *m.CreateUser
	}
	return ""
}

func (m *ModuleMachine) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

type ModuleInfo struct {
	ModuleId         *string          `protobuf:"bytes,1,req,name=module_id" json:"module_id,omitempty"`
	ModuleName       *string          `protobuf:"bytes,2,opt,name=module_name" json:"module_name,omitempty"`
	ModuleDesc       *string          `protobuf:"bytes,3,opt,name=module_desc" json:"module_desc,omitempty"`
	CreateUser       *string          `protobuf:"bytes,4,opt,name=create_user" json:"create_user,omitempty"`
	CreateTime       *string          `protobuf:"bytes,5,opt,name=create_time" json:"create_time,omitempty"`
	MachineList      []*ModuleMachine `protobuf:"bytes,6,rep,name=machine_list" json:"machine_list,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ModuleInfo) Reset()                    { *m = ModuleInfo{} }
func (m *ModuleInfo) String() string            { return proto.CompactTextString(m) }
func (*ModuleInfo) ProtoMessage()               {}
func (*ModuleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModuleInfo) GetModuleId() string {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return ""
}

func (m *ModuleInfo) GetModuleName() string {
	if m != nil && m.ModuleName != nil {
		return *m.ModuleName
	}
	return ""
}

func (m *ModuleInfo) GetModuleDesc() string {
	if m != nil && m.ModuleDesc != nil {
		return *m.ModuleDesc
	}
	return ""
}

func (m *ModuleInfo) GetCreateUser() string {
	if m != nil && m.CreateUser != nil {
		return *m.CreateUser
	}
	return ""
}

func (m *ModuleInfo) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

func (m *ModuleInfo) GetMachineList() []*ModuleMachine {
	if m != nil {
		return m.MachineList
	}
	return nil
}

type GetRouteRequest struct {
	ModuleId         *string `protobuf:"bytes,1,req,name=module_id" json:"module_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRouteRequest) Reset()                    { *m = GetRouteRequest{} }
func (m *GetRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRouteRequest) ProtoMessage()               {}
func (*GetRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRouteRequest) GetModuleId() string {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return ""
}

type GetRouteResponse struct {
	Code             *int32  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRouteResponse) Reset()                    { *m = GetRouteResponse{} }
func (m *GetRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRouteResponse) ProtoMessage()               {}
func (*GetRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRouteResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *GetRouteResponse) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

type GetModuleRouteListRequest struct {
	ModuleId         *string `protobuf:"bytes,1,req,name=module_id" json:"module_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetModuleRouteListRequest) Reset()                    { *m = GetModuleRouteListRequest{} }
func (m *GetModuleRouteListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetModuleRouteListRequest) ProtoMessage()               {}
func (*GetModuleRouteListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetModuleRouteListRequest) GetModuleId() string {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return ""
}

type GetModuleRouteListResponse struct {
	Code             *int32      `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Module           *ModuleInfo `protobuf:"bytes,2,req,name=module" json:"module,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetModuleRouteListResponse) Reset()                    { *m = GetModuleRouteListResponse{} }
func (m *GetModuleRouteListResponse) String() string            { return proto.CompactTextString(m) }
func (*GetModuleRouteListResponse) ProtoMessage()               {}
func (*GetModuleRouteListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetModuleRouteListResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *GetModuleRouteListResponse) GetModule() *ModuleInfo {
	if m != nil {
		return m.Module
	}
	return nil
}

type UpdateRouteRequest struct {
	ModuleId         *string `protobuf:"bytes,1,req,name=module_id" json:"module_id,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Status           *int32  `protobuf:"varint,3,req,name=status" json:"status,omitempty"`
	Timeout          *int32  `protobuf:"varint,4,req,name=timeout" json:"timeout,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateRouteRequest) Reset()                    { *m = UpdateRouteRequest{} }
func (m *UpdateRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRouteRequest) ProtoMessage()               {}
func (*UpdateRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRouteRequest) GetModuleId() string {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return ""
}

func (m *UpdateRouteRequest) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *UpdateRouteRequest) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *UpdateRouteRequest) GetTimeout() int32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type UpdateRouteResponse struct {
	Code             *int32  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Error            *string `protobuf:"bytes,2,req,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateRouteResponse) Reset()                    { *m = UpdateRouteResponse{} }
func (m *UpdateRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateRouteResponse) ProtoMessage()               {}
func (*UpdateRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRouteResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *UpdateRouteResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type ReLoadRouteNotify struct {
	ModuleId         *string `protobuf:"bytes,1,req,name=module_id" json:"module_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReLoadRouteNotify) Reset()                    { *m = ReLoadRouteNotify{} }
func (m *ReLoadRouteNotify) String() string            { return proto.CompactTextString(m) }
func (*ReLoadRouteNotify) ProtoMessage()               {}
func (*ReLoadRouteNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReLoadRouteNotify) GetModuleId() string {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return ""
}

type Request struct {
	Cmd              *int32  `protobuf:"varint,1,req,name=cmd" json:"cmd,omitempty"`
	Body             *string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Request) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Request) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

type Response struct {
	Code             *int32  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Response         *string `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Response) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Response) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "router.Test")
	proto.RegisterType((*Test_OptionalGroup)(nil), "router.Test.OptionalGroup")
	proto.RegisterType((*ModuleMachine)(nil), "router.ModuleMachine")
	proto.RegisterType((*ModuleInfo)(nil), "router.ModuleInfo")
	proto.RegisterType((*GetRouteRequest)(nil), "router.GetRouteRequest")
	proto.RegisterType((*GetRouteResponse)(nil), "router.GetRouteResponse")
	proto.RegisterType((*GetModuleRouteListRequest)(nil), "router.GetModuleRouteListRequest")
	proto.RegisterType((*GetModuleRouteListResponse)(nil), "router.GetModuleRouteListResponse")
	proto.RegisterType((*UpdateRouteRequest)(nil), "router.UpdateRouteRequest")
	proto.RegisterType((*UpdateRouteResponse)(nil), "router.UpdateRouteResponse")
	proto.RegisterType((*ReLoadRouteNotify)(nil), "router.ReLoadRouteNotify")
	proto.RegisterType((*Request)(nil), "router.Request")
	proto.RegisterType((*Response)(nil), "router.Response")
	proto.RegisterEnum("router.FOO", FOO_name, FOO_value)
}

func init() { proto.RegisterFile("router.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdd, 0x6a, 0xdb, 0x40,
	0x10, 0x85, 0xd1, 0x9f, 0x13, 0x8f, 0xa5, 0xc6, 0xde, 0x10, 0xd8, 0xfa, 0x4a, 0x2c, 0x21, 0x88,
	0xb4, 0x18, 0xea, 0x9b, 0x40, 0x1f, 0x20, 0xa6, 0x90, 0xc4, 0x60, 0x1c, 0xe8, 0x9d, 0x51, 0xb4,
	0xe3, 0x64, 0x41, 0xd2, 0xaa, 0xbb, 0x2b, 0x8a, 0xdf, 0xa2, 0x8f, 0xd0, 0x47, 0x2d, 0x2b, 0xc9,
	0x75, 0xdc, 0xaa, 0xcd, 0x9d, 0x7d, 0xf6, 0xcc, 0x7c, 0x33, 0x67, 0x04, 0xa1, 0x92, 0xb5, 0x41,
	0x35, 0xab, 0x94, 0x34, 0x92, 0x0c, 0xda, 0x7f, 0xec, 0x87, 0x03, 0xfe, 0x1a, 0xb5, 0x21, 0x11,
	0x04, 0x79, 0xfa, 0x84, 0x39, 0x75, 0x62, 0x37, 0x19, 0x92, 0x31, 0xf8, 0x66, 0x57, 0x21, 0x75,
	0x63, 0x27, 0x09, 0x3e, 0xbb, 0x37, 0x37, 0x24, 0x04, 0x5f, 0x61, 0xa5, 0xa9, 0x17, 0x7b, 0x89,
	0x47, 0x3e, 0x41, 0x24, 0x2b, 0x23, 0x64, 0x99, 0xe6, 0xcf, 0x4a, 0xd6, 0x15, 0xf5, 0x63, 0x27,
	0x81, 0xf9, 0x74, 0xd6, 0x51, 0x6c, 0xcf, 0xd9, 0xb2, 0x73, 0x2c, 0xac, 0x63, 0x7a, 0x05, 0xd1,
	0x91, 0x40, 0x2e, 0x20, 0x5a, 0xe1, 0xb7, 0x5a, 0x28, 0xe4, 0xb7, 0x02, 0x73, 0x4e, 0x03, 0x8b,
	0x66, 0x5b, 0x88, 0xee, 0x25, 0xaf, 0x73, 0xbc, 0x4f, 0xb3, 0x17, 0x51, 0x22, 0x99, 0xc0, 0xb0,
	0x68, 0x84, 0x8d, 0xe0, 0xdd, 0x78, 0x00, 0xae, 0xa8, 0xa8, 0xdb, 0xfc, 0x7e, 0x07, 0x83, 0xef,
	0x28, 0x9e, 0x5f, 0x0c, 0xf5, 0x62, 0x37, 0x09, 0x08, 0x01, 0xc8, 0x14, 0xa6, 0x06, 0x1f, 0x35,
	0xaa, 0x66, 0xae, 0xe1, 0x41, 0x5b, 0x8b, 0x02, 0x69, 0x60, 0x35, 0xf6, 0xd3, 0x01, 0x68, 0x41,
	0x5f, 0xca, 0xad, 0xec, 0xa3, 0x9c, 0xc3, 0xa8, 0x93, 0xca, 0xb4, 0x68, 0xb3, 0x78, 0x2d, 0x72,
	0xd4, 0x19, 0xf5, 0xf6, 0x62, 0xdb, 0x7f, 0x53, 0x1f, 0xa0, 0x07, 0xd1, 0xfc, 0xa6, 0x92, 0x0f,
	0x10, 0x16, 0xed, 0x5e, 0x9b, 0x5c, 0x68, 0x43, 0x07, 0xb1, 0x97, 0x8c, 0xe6, 0x17, 0xfb, 0xdc,
	0x8e, 0x36, 0x67, 0x97, 0x70, 0xb6, 0x40, 0xb3, 0xb2, 0x4f, 0x36, 0x29, 0x7b, 0xa7, 0xbf, 0xc7,
	0x64, 0x1f, 0x61, 0x7c, 0x70, 0xe9, 0x4a, 0x96, 0x1a, 0xed, 0xb5, 0x32, 0xc9, 0xb1, 0x71, 0x04,
	0xaf, 0xe3, 0x62, 0x33, 0x78, 0xbf, 0x40, 0xd3, 0x72, 0x9a, 0x9a, 0x3b, 0xa1, 0xcd, 0x7f, 0xba,
	0x3f, 0xc0, 0xb4, 0xcf, 0xdf, 0xcb, 0x61, 0x30, 0x68, 0xcb, 0x1b, 0xd6, 0x68, 0x4e, 0x8e, 0xd7,
	0xb2, 0x39, 0xb3, 0x35, 0x90, 0xc7, 0x8a, 0xa7, 0x06, 0xdf, 0x58, 0xeb, 0xcf, 0x1b, 0x6b, 0x93,
	0x9a, 0x5a, 0x77, 0x37, 0x3e, 0x83, 0x13, 0x9b, 0xa9, 0xac, 0x0d, 0xf5, 0xad, 0xc0, 0xe6, 0x70,
	0x7e, 0xd4, 0xb5, 0x77, 0xbc, 0x08, 0x02, 0x54, 0x4a, 0xaa, 0x2e, 0x89, 0x2b, 0x98, 0xac, 0xf0,
	0x4e, 0xa6, 0xbc, 0xa9, 0x79, 0x90, 0x46, 0x6c, 0x77, 0x7d, 0x09, 0x5c, 0xc2, 0xc9, 0x7e, 0xcc,
	0x11, 0x78, 0x59, 0xc1, 0xbb, 0x76, 0x21, 0xf8, 0x4f, 0x92, 0xef, 0xda, 0xef, 0x82, 0x5d, 0xc3,
	0xe9, 0x3f, 0xb0, 0x63, 0x38, 0x55, 0xdd, 0x4b, 0xeb, 0xbd, 0x0e, 0xc1, 0xbb, 0x5d, 0x2e, 0x49,
	0x00, 0xce, 0xd7, 0xf1, 0xe4, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0xbf, 0xaa, 0x3f, 0x9a,
	0x03, 0x00, 0x00,
}
